============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.3.1, pluggy-1.0.0 -- /home/tatchisabato/.pyenv/versions/3.10.6/envs/taxifare-env/bin/python3.10
cachedir: .pytest_cache
rootdir: /home/tatchisabato/cloud-training/tests
configfile: pytest_kitt.ini
collecting ... collected 9 items

tests/cloud_training/test_cloud_data.py::TestCloudData::test_big_query_dataset_variable_exists PASSED [ 11%]
tests/cloud_training/test_cloud_data.py::TestCloudData::test_cloud_data_create_dataset PASSED [ 22%]
tests/cloud_training/test_cloud_data.py::TestCloudData::test_cloud_data_create_table PASSED [ 33%]
tests/cloud_training/test_main.py::TestMain::test_route_preprocess PASSED [ 44%]
tests/cloud_training/test_main.py::TestMain::test_route_train[local] PASSED [ 55%]
tests/cloud_training/test_main.py::TestMain::test_route_train[gcs] PASSED [ 66%]
tests/cloud_training/test_main.py::TestMain::test_route_evaluate PASSED  [ 77%]
tests/cloud_training/test_main.py::TestMain::test_route_pred PASSED      [ 88%]
tests/cloud_training/test_vm.py::test_i_am_a_vm PASSED                   [100%]

======================= 9 passed, 18 warnings in 27.94s ========================
